project_id = "vpsbqrxrjrwjmttnptfr"

[functions.chat]
verify_jwt = false

[functions.generate-quote-pdf]
verify_jwt = false

[functions.generate-service-images]
verify_jwt = false

[functions.create-team-member]
verify_jwt = false
